dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=1

  # Main test targets
  # get versions from: https://opam.ocaml.org/packages/coq/
  # Only use versions that CompCert can build with...
  matrix:
  - COMPILER="4.12.0"
    TEST_TARGET="8.14.1"
  - COMPILER="4.12.0"
    TEST_TARGET="8.15.0"
  - COMPILER="4.12.0"
    TEST_TARGET="dev"

install:
  - opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
  - eval $(opam config env)
  - opam config var root
  - opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y

script:
  - eval $(opam config env)
  - opam config var root
  - make -j ${NJOBS} -C src/
