dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=1

  # Main test targets
  # get versions from: https://opam.ocaml.org/packages/coq/
  # Only use versions that CompCert can build with...
  matrix:
  - COMPILER="4.09.1"
    TEST_TARGET="8.9.0"
  - COMPILER="4.09.1"
    TEST_TARGET="8.10.0"
  - COMPILER="4.09.1"
    TEST_TARGET="8.11.0"
  - COMPILER="4.10.0"
    TEST_TARGET="8.12.0"

install:
  - opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
  - eval $(opam config env)
  - opam config var root
  - opam install -y --verbose -j ${NJOBS} coq.${TEST_TARGET} && opam pin add coq ${TEST_TARGET} -y

script:
  - eval $(opam config env)
  - opam config var root
  - make -j ${NJOBS} -C src/
